### ISSUE TITLE
Typos.....

### ISSUE THREAD

**Issue by sooklald** [learn-co-curriculum/dsc-0-10-05-stats-learning-theory#2]
Non-existent c referenced in description, none shown in formula. Anyone who knows slope of a line will recognize this, but proofread material would be nice.

![image](https://user-images.githubusercontent.com/42424167/48168090-fb704200-e2bb-11e8-884e-cf7ad323c1d7.png)

**Comment by ShakeelRaja** [comment]
fixed notation inconsistencies
